### ISSUE TITLE
Previous month button work only for payout

### ISSUE THREAD

**Issue by MaxMaximus** [TonyTosol/StorJ-Audit#6]
Hello

Previous month button in Storj-Audit app gets previous month data only for payout column. All other stats (all bandwidth columns and used space)  still shown for current month - no any difference with "get data".
Is it a Storj API limitation or a bug in Storj-Audit?

**Comment by TonyTosol** [comment]
Yes it show only payout for last month, there is no stats in API for last month only payouts.

**Comment by MaxMaximus** [comment]
I see. I have carefully checked the API and there really is no any data on traffic and volume of stored data for the previous month. While this info is still in the node DB and partially accessible via GUI dashboard.  But not via API for some reason...

But during the check, as a side result, I found out that the audit stats is actually in the API. In one of the previous versions of the utility, you disabled the output of audit statistics, referring to the fact that this information was removed from the node API. 

It looks like it was either returned back or not removed at all, but simply changed the format, which is why the previous requests stopped working. Probably when they changed the logic of the auditor's work, combining audits with checking node uptime stats. There are no separate online checks, uptime calculated as successful/total audits ratio.  Now this is a single statistic and can be obtain via such url requests:
<nodeip>:14002/api/sno/satellite/<satellite_id>
(same as daily stats on bandwith for individual satellite, just in the another sections of JSON response)

Example:
```
  "audits": {
    "auditScore": 1,
    "suspensionScore": 1,
    "onlineScore": 0.9906430932184375,
    "satelliteName": "europe-north-1.tardigrade.io:7777"
  },
  "auditHistory": {
    "score": 0.9906430932184375,
    "windows": [
      {
        "windowStart": "2023-03-25T00:00:00Z",
        "totalCount": 115,
        "onlineCount": 115
      },
      {
        "windowStart": "2023-03-25T12:00:00Z",
        "totalCount": 132,
        "onlineCount": 132
      },
      {
        "windowStart": "2023-03-26T00:00:00Z",
        "totalCount": 113,
        "onlineCount": 113
      },
      {
        "windowStart": "2023-03-26T12:00:00Z",
        "totalCount": 117,
        "onlineCount": 103
      },
```
It's just that now there are no two ready-to-use numbers showing the total/successful number of audit requests for satellite. But only detailed statistics broken down into 60 intervals of 12 hours each. Which represents the last 30 days (not the current or last month, but namely the last 30 days - a rolling 30-day "window"). 

So, if there is free time and a desire to do it, it is possible to restore the output of audit statistics for monitoring. It's just that now this will require a cycle summing 60 values twice into 2 sums (total/successful).

**Comment by TonyTosol** [comment]
thank you, I managed to make it. soon will publish it.

**Comment by MaxMaximus** [comment]
Just tested it on my 3 nodes. Audit data collection now works fine in the new v.1.7!
Although in the process of checking, I found a bug with other data. But it has nothing to do with audits or traffic, so I'll describe it in a separate issue. This one is resolved.
