### ISSUE TITLE
Incorrect values in TB*Month column

### ISSUE THREAD

**Issue by MaxMaximus** [TonyTosol/StorJ-Audit#7]
Hello.

I I found that all values in `TB*Month` column of Storj-Audit app are completely wrong. For example it shows now 34 `TB*month` for current month for a node which stores just about 1.8 TB data total and 122 `TB*Month` for node with 7.2 TB of data stored:
![Audit](https://user-images.githubusercontent.com/6316214/234270856-302c086b-2484-452c-b060-8a8ecddd9bb9.png)

I checked the code and found the cause of the error, there was an unnecessary multiplication by 24 in the code when converting from `bytes * hours` returned by the API to `TB*Month`

**Comment by MaxMaximus** [comment]
I tried to fix the code myself, at the same time added the missing output of TB*Month statistics for individual satellites. There is my variant in pull request #8 
However, I did not check the work and did not debug it, I do not have an IDE for VB net installed, so I wrote this code just in a text editor. So it may contain some new error, check it first.

**Comment by TonyTosol** [comment]
changed according Storj changed it in API
